customhost = "employee.cotehfneowq8.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chowwengyong-employee"
customregion = "us-east-1"
